from __future__ import annotations

from collections.abc import Iterator, Mapping
from types import TracebackType
from typing import Any, overload

import numpy as np
from numpy.typing import DTypeLike, NDArray

from . import h5f as h5f

class AttributeManager(Mapping[str, "Empty | np.generic | NDArray[np.generic] | str"]):
    def __getitem__(self, key: str) -> Empty | np.generic | NDArray[np.generic] | str: ...
    def __setitem__(self, key: str, value: object) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...

class Empty:
    def __init__(self, dtype: DTypeLike) -> None: ...

class HLObject:
    @property
    def name(self) -> str: ...
    @property
    def attrs(self) -> AttributeManager: ...
    @property
    def file(self) -> File: ...

class Dataset(HLObject):
    @property
    def dtype(self) -> np.dtype[np.generic]: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @overload
    def resize(self, size: int, axis: int) -> None: ...
    @overload
    def resize(self, size: tuple[int, ...], axis: None = None) -> None: ...
    @overload
    def __getitem__(self, selector: slice | NDArray[np.integer[Any]]) -> NDArray[np.generic]: ...
    @overload
    def __getitem__(self, selector: tuple[()]) -> NDArray[np.generic] | np.generic: ...
    def __setitem__(self, selector: object, value: object) -> None: ...

class Group(HLObject, Mapping[str, "Group | Dataset"]):
    def __getitem__(self, name: str) -> Group | Dataset: ...
    def __setitem__(self, name: str, obj: object) -> None: ...
    def __delitem__(self, name: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def create_group(self, name: str) -> Group: ...
    def require_group(self, name: str) -> Group: ...
    def create_dataset(
        self,
        name: str | None,
        shape: int | tuple[int, ...] | None = None,
        maxshape: tuple[int | None, ...] | None = None,
        chunks: tuple[int, ...] | bool | None = None,
        dtype: DTypeLike | None = None,
        data: NDArray[np.generic] | None = None,
    ) -> Dataset: ...

class _FileCreationPropertyList:
    def get_file_space_strategy(self) -> tuple[int, bool, int]: ...

class _FileID:
    def get_create_plist(self) -> _FileCreationPropertyList: ...

class File(Group):
    def __init__(self, name: str, mode: str = "r", locking: bool | None = None, **kwargs: object) -> None: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    def __enter__(self) -> File: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    @property
    def id(self) -> _FileID: ...
